apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t0ohge8yq-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:e4f93875dc4fdd04cd716a9d3f9fde8f8265b996@sha256:28f38eab4e80cc5b31afa050d9fea8390133ecce0558f36035cf208a4876c007
          name: container-image
